site_name: Linwood
site_url: https://linwood.tk
repo_url: https://github.com/codedoctorde/Linwood/
theme:
  name: 'readthedocs'
  highlightjs: true
markdown_extensions:
  - codehilite
nav:
  - Home: "wiki/index.md"
  - Teams:
      - Commands: "wiki/teams/commands"